markdown: rdiscount
permalink: /:year/:month/:day/:title/

name: "Yang Liu"

author: "Yang Liu"
atom-baseurl: "http://clairely.github.io"
disqus: "zagol"


pygments: true
safe: true
paginate: 16
auto: true

